
export const sampleCars = [
    {
        id: "1e8a8b1a-4b3b-4c8d-9d4a-3a1b2c3d4e5f",
        make: "Porsche",
        model: "911 GT3",
        year: 2023,
        price: 250000,
        mileage: 1500,
        color: "Shark Blue",
        imageUrl: "https://images.unsplash.com/photo-1613921568536-555645be4032?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxwb3JzY2hlJTIwOTExfGVufDB8fHx8MTc2MjQyODcxMnww&ixlib.rb-4.1.0&q=80&w=1080",
        description: "The Porsche 911 GT3 is a high-performance homologation model of the Porsche 911 sports car. It is a line of high-performance models, which began with the 1973 911 Carrera RS.",
        engine: "4.0L Flat-6",
        horsepower: 502,
        transmission: "PDK or Manual"
    },
    {
        id: "2a3b4c5d-6e7f-8g9h-0i1j-2k3l4m5n6o7p",
        make: "Ferrari",
        model: "F8 Tributo",
        year: 2022,
        price: 350000,
        mileage: 800,
        color: "Rosso Corsa",
        imageUrl: "https://cdn.ferrari.com/cms/network/media/img/resize/63c5153bde3d8c00233f408c-ferrari-genuine-f8-tributo-social-card-page?width=1080",
        description: "The Ferrari F8 Tributo is a mid-engine sports car produced by the Italian automobile manufacturer Ferrari. The car is an update to the 488 GTB, with notable exterior and performance changes.",
        engine: "3.9L Twin-Turbo V8",
        horsepower: 710,
        transmission: "7-Speed Dual-Clutch"
    },
    {
        id: "3b4c5d6e-7f8g-9h0i-1j2k-3l4m5n6o7p8q",
        make: "Lamborghini",
        model: "Huracan STO",
        year: 2023,
        price: 400000,
        mileage: 500,
        color: "Verde Citrea",
        imageUrl: "https://images.unsplash.com/photo-1696581082291-5230d4de01c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxsYW1ib3JnaGluaSUyMHllbGxvd3xlbnwwfHx8fDE3NjI0NDMyNjl8MA&ixlib.rb-4.1.0&q=80&w=1080",
        description: "The Lamborghini Huracán STO (Super Trofeo Omologata) is a rear-wheel drive, track-focused variant of the Huracán. It is powered by the same 5.2-litre naturally-aspirated V10 engine as the Huracán EVO and Performante.",
        engine: "5.2L V10",
        horsepower: 631,
        transmission: "7-Speed Dual-Clutch"
    },
    {
        id: "4c5d6e7f-8g9h-0i1j-2k3l-4m5n6o7p8q9r",
        make: "McLaren",
        model: "720S",
        year: 2021,
        price: 315000,
        mileage: 2200,
        color: "McLaren Orange",
        imageUrl: "https://s1.paultan.org/image/2017/03/McLaren-720S-1.jpg",
        description: "The McLaren 720S is a British sports car designed and manufactured by McLaren Automotive. It is the second all-new car in the McLaren Super Series, replacing the 650S.",
        engine: "4.0L Twin-Turbo V8",
        horsepower: 710,
        transmission: "7-Speed Dual-Clutch"
    },
    {
        id: "5d6e7f8g-9h0i-1j2k-3l4m-5n6o7p8q9r0s",
        make: "Aston Martin",
        model: "Vantage",
        year: 2024,
        price: 190000,
        mileage: 100,
        color: "Lime Essence",
        imageUrl: "https://s.yimg.com/ny/api/res/1.2/.ORvSdbC9wguST64zEGi.Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/autocar_articles_778/bf231825b0f6fc72076d9382a1518dd8",
        description: "The Aston Martin Vantage is a two-seater sports car manufactured by British luxury car manufacturer Aston Martin. Aston Martin has previously used the 'Vantage' name on high-performance variants of their existing GT models.",
        engine: "4.0L Twin-Turbo V8",
        horsepower: 656,
        transmission: "8-Speed Automatic"
    },
    {
        id: "6e7f8g9h-0i1j-2k3l-4m5n-6o7p8q9r0s1t",
        make: "Audi",
        model: "R8",
        year: 2023,
        price: 180000,
        mileage: 3000,
        color: "Vegas Yellow",
        imageUrl: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhdWRpJTIwcjhlbnwwfHx8fDE3NjMwNzc3MjV8MA&ixlib.rb-4.1.0&q=80&w=1080",
        description: "The Audi R8 is a mid-engine, 2-seater sports car, which uses Audi's trademark quattro permanent all-wheel drive system. It was introduced by the German car manufacturer Audi AG in 2006.",
        engine: "5.2L V10",
        horsepower: 602,
        transmission: "7-Speed S tronic"
    },
    {
        id: "7f8g9h0i-1j2k-3l4m-5n6o-7p8q9r0s1t2u",
        make: "BMW",
        model: "M4 Competition",
        year: 2023,
        price: 95000,
        mileage: 5000,
        color: "Isle of Man Green",
        imageUrl: "https://www.slashgear.com/img/gallery/2023-bmw-m4-csl-review-brutally-good/l-intro-1676043003.jpg",
        description: "The BMW M4 Competition is a high-performance version of the BMW 4 Series coupe. It features a more powerful engine, sport-tuned suspension, and aggressive styling.",
        engine: "3.0L Twin-Turbo I6",
        horsepower: 503,
        transmission: "8-Speed M Steptronic"
    },
    {
        id: "8g9h0i1j-2k3l-4m5n-6o7p-8q9r0s1t2u3v",
        make: "Mercedes-AMG",
        model: "GT",
        year: 2024,
        price: 185000,
        mileage: 200,
        color: "designo Selenite Grey Magno",
        imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "The Mercedes-AMG GT is a grand tourer sports car produced in-house by Mercedes-AMG. It combines the fascination of a genuine sports car with segment-specific technology.",
        engine: "4.0L Twin-Turbo V8",
        horsepower: 577,
        transmission: "9-Speed MCT"
    },
    {
        id: "9h0i1j2k-3l4m-5n6o-7p8q-9r0s1t2u3v4w",
        make: "Chevrolet",
        model: "Corvette Z06",
        year: 2023,
        price: 110000,
        mileage: 1200,
        color: "Torch Red",
        imageUrl: "https://www.carscoops.com/wp-content/uploads/2023/07/Corvette-Z06a.jpg",
        description: "The Chevrolet Corvette Z06 is a high-performance version of the Corvette sports car with a focus on track capability. It features a naturally aspirated flat-plane crank V8.",
        engine: "5.5L LT6 V8",
        horsepower: 670,
        transmission: "8-Speed Dual-Clutch"
    },
    {
        id: "0i1j2k3l-4m5n-6o7p-8q9r-0s1t2u3v4w5x",
        make: "Nissan",
        model: "GT-R Nismo",
        year: 2024,
        price: 220000,
        mileage: 400,
        color: "Stealth Gray",
        imageUrl: "https://4kwallpapers.com/images/wallpapers/nissan-gt-r-nismo-1920x1200-10197.jpeg",
        description: "The Nissan GT-R Nismo is the pinnacle of the GT-R lineup, offering blistering performance through advanced aerodynamics and a finely-tuned suspension. It's a supercar for the true driving enthusiast.",
        engine: "3.8L Twin-Turbo V6",
        horsepower: 600,
        transmission: "6-Speed Dual-Clutch"
    },
    {
        id: "1j2k3l4m-5n6o-7p8q-9r0s-1t2u3v4w5x6y",
        make: "Ford",
        model: "Shelby GT500",
        year: 2022,
        price: 85000,
        mileage: 4000,
        color: "Race Red",
        imageUrl: "https://www.carscoops.com/wp-content/uploads/2019/09/3f2ff3ff-ford-mustang-shelby-gt500.jpg",
        description: "The Ford Mustang Shelby GT500 is the most powerful street-legal Ford ever built. It's a track-ready beast with a supercharged V8 engine and an aggressive aerodynamic design.",
        engine: "5.2L Supercharged V8",
        horsepower: 760,
        transmission: "7-Speed Dual-Clutch"
    },
    {
        id: "2k3l4m5n-6o7p-8q9r-0s1t-2u3v4w5x6y7z",
        make: "Toyota",
        model: "GR Supra",
        year: 2024,
        price: 60000,
        mileage: 800,
        color: "Renaissance Red 2.0",
        imageUrl: "https://www.topgear.com/sites/default/files/2022/06/16-Toyota-GR-Supra.jpg",
        description: "The Toyota GR Supra is a thrilling sports car with a legendary name. Co-developed with BMW, it offers a potent turbocharged engine, rear-wheel-drive dynamics, and a striking design.",
        engine: "3.0L Turbo I6",
        horsepower: 382,
        transmission: "8-Speed Automatic"
    }
];
